Trekstore/Models/PurchaseDetails.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Trekstore.Models
{
    public class PurchaseDetails
    {
        [Key] public int purch_id { get; set; }

        public int Amount { get; set; }

        public DateTime PurchDate { get; set; }

         public int? ProductID { get; set; }

        public int? ProviderID{ get; set; }

        public int? TipoDePagoID { get; set; }

        public virtual Products? Product{ get; set; }

        public virtual Providers? Provider { get; set; }

        public virtual TipoDePago? TipoDePago { get; set; }

    }
}

Trekstore/Controllers/ProvidersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Trekstore.Areas.Identity.Data;
using Trekstore.Models;

namespace Trekstore.Controllers
{
    public class ProvidersController : Controller
    {
        private readonly TrekstorDbContext _context;

        public ProvidersController(TrekstorDbContext context)
        {
            _context = context;
        }
        [Authorize(Roles = "Administrador")]
        // GET: Providers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Providers.ToListAsync());
        }

        // GET: Providers/Details/5
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var providers = await _context.Providers
                .FirstOrDefaultAsync(m => m.ProviderID == id);
            if (providers == null)
            {
                return NotFound();
            }

            return View(providers);
        }

        // GET: Providers/Create
        [Authorize(Roles = "Administrador")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Providers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrador")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProviderID,Name,Telephone,Address")] Providers providers)
        {
            if (ModelState.IsValid)
            {
                _context.Add(providers);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(providers);
        }

        // GET: Providers/Edit/5
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var providers = await _context.Providers.FindAsync(id);
            if (providers == null)
            {
                return NotFound();
            }
            return View(providers);
        }

        // POST: Providers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrador")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProviderID,Name,Telephone,Address")] Providers providers)
        {
            if (id != providers.ProviderID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(providers);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProvidersExists(providers.ProviderID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(providers);
        }

        // GET: Providers/Delete/5
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var providers = await _context.Providers
                .FirstOrDefaultAsync(m => m.ProviderID == id);
            if (providers == null)
            {
                return NotFound();
            }

            return View(providers);
        }

        // POST: Providers/Delete/5
        [Authorize(Roles = "Administrador")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var providers = await _context.Providers.FindAsync(id);
            if (providers != null)
            {
                _context.Providers.Remove(providers);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProvidersExists(int id)
        {
            return _context.Providers.Any(e => e.ProviderID == id);
        }
    }
}

Trekstore/Controllers/PurchaseDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Trekstore.Areas.Identity.Data;
using Trekstore.Models;

namespace Trekstore.Controllers
{

    public class PurchaseDetailsController : Controller
    {

        private readonly TrekstorDbContext _context;

        public PurchaseDetailsController(TrekstorDbContext context)
        {
            _context = context;
        }
        [Authorize(Roles = "Administrador, Supervisor")]
        // GET: PurchaseDetails
        public async Task<IActionResult> Index(string searchString, DateTime? startDate, DateTime? endDate)
        {
            ViewData["CurrentFilter"] = searchString;
            ViewData["CurrentStartDate"] = startDate?.ToString("yyyy-MM-dd");
            ViewData["CurrentEndDate"] = endDate?.ToString("yyyy-MM-dd");

            var purchaseDetails = _context.PurchaseDetails
                                           .Include(p => p.Product)
                                           .Include(p => p.Provider)
                                           .Include(p => p.TipoDePago)
                                           .AsQueryable();

            if (!String.IsNullOrEmpty(searchString))
            {
                purchaseDetails = purchaseDetails.Where(s => s.Product.ProductName.Contains(searchString));
            }

            if (startDate.HasValue && endDate.HasValue)
            {
                purchaseDetails = purchaseDetails.Where(p => p.PurchDate >= startDate && p.PurchDate <= endDate);
            }

            return View(await purchaseDetails.ToListAsync());
        }

        [Authorize(Roles = "Administrador")]
        // GET: PurchaseDetails/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var purchaseDetails = await _context.PurchaseDetails
                .Include(p => p.Product)
                .Include(p => p.Provider)
                .Include(p => p.TipoDePago)
                .FirstOrDefaultAsync(m => m.purch_id == id);
            if (purchaseDetails == null)
            {
                return NotFound();
            }

            return View(purchaseDetails);
        }

        // GET: PurchaseDetails/Create
        [Authorize(Roles = "Administrador, Ventas")]
        public IActionResult Create()
        {
            ViewData["ProductID"] = new SelectList(_context.Products, "ProductId", "ProductName");
            ViewData["ProviderID"] = new SelectList(_context.Providers, "ProviderID", "Name");
            ViewData["TipoDePagoID"] = new SelectList(_context.TipoDePago, "tipoPagoID", "tipoPago");

            return View();
        }

        // POST: PurchaseDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador, Ventas")]
        public async Task<IActionResult> Create([Bind("purch_id,Amount,PurchDate,ProductID,ProviderID, TipoDePagoID")] PurchaseDetails purchaseDetails)
        {
            if (ModelState.IsValid)
            {
                var product = await _context.Products.FindAsync(purchaseDetails.ProductID);

                product.InStock += purchaseDetails.Amount;
                _context.Add(purchaseDetails);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

            }
            ViewData["ProductID"] = new SelectList(_context.Products, "ProductId", "ProductName", purchaseDetails.ProductID);
            ViewData["ProviderID"] = new SelectList(_context.Providers, "ProviderID", "Name", purchaseDetails.ProviderID);
            ViewData["TipoDePagoID"] = new SelectList(_context.TipoDePago, "tipoPagoID", "tipoPago", purchaseDetails.TipoDePagoID);
            return View(purchaseDetails);
        }

        // GET: PurchaseDetails/Edit/5
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var purchaseDetails = await _context.PurchaseDetails.FindAsync(id);
            if (purchaseDetails == null)
            {
                return NotFound();
            }
            ViewData["ProductID"] = new SelectList(_context.Products, "ProductId", "ProductName", purchaseDetails.ProductID);
            ViewData["ProviderID"] = new SelectList(_context.Providers, "ProviderID", "Name", purchaseDetails.ProviderID);
            ViewData["TipoDePagoID"] = new SelectList(_context.TipoDePago, "tipoPagoID", "tipoPago", purchaseDetails.TipoDePagoID);
            return View(purchaseDetails);
        }

        // POST: PurchaseDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrador")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("purch_id,Amount,PurchDate,ProductID,ProviderID, tipoPagoID")] PurchaseDetails purchaseDetails)
        {
            if (id != purchaseDetails.purch_id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(purchaseDetails);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PurchaseDetailsExists(purchaseDetails.purch_id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductID"] = new SelectList(_context.Products, "ProductId", "ProductName", purchaseDetails.Product);
            ViewData["ProviderID"] = new SelectList(_context.Providers, "ProviderID", "Name", purchaseDetails.ProviderID);
            ViewData["TipoDePagoID"] = new SelectList(_context.TipoDePago, "tipoPagoID", "tipoPago", purchaseDetails.TipoDePagoID);
            return View(purchaseDetails);
        }

        // GET: PurchaseDetails/Delete/5
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var purchaseDetails = await _context.PurchaseDetails
                .Include(p => p.Product)
                .Include(p => p.Provider)
                .Include(p=> p.TipoDePago)
                .FirstOrDefaultAsync(m => m.purch_id == id);
            if (purchaseDetails == null)
            {
                return NotFound();
            }

            return View(purchaseDetails);
        }

        // POST: PurchaseDetails/Delete/5
        [Authorize(Roles = "Administrador")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var purchaseDetails = await _context.PurchaseDetails.FindAsync(id);
            if (purchaseDetails != null)
            {
                _context.PurchaseDetails.Remove(purchaseDetails);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PurchaseDetailsExists(int id)
        {
            return _context.PurchaseDetails.Any(e => e.purch_id == id);
        }
    }
}

Trekstore/Views/PurchaseDetails/Create.cshtml
@model Trekstore.Models.PurchaseDetails

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Agregar Compra</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label">Cantidad</label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PurchDate" class="control-label">Fecha de Compra</label>
                <input asp-for="PurchDate" class="form-control" />
                <span asp-validation-for="PurchDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductID" class="control-label">Producto</label>
                <select asp-for="ProductID" class="form-control" asp-items="ViewBag.ProductID"></select>
            </div>
            <div class="form-group">
                <label asp-for="ProviderID" class="control-label">Proveedor</label>
                <select asp-for="ProviderID" class="form-control" asp-items="ViewBag.ProviderID"></select>
            </div>
            <div class="form-group">
                <label asp-for="TipoDePagoID" class="control-label"></label>
                <select asp-for="TipoDePagoID" class="form-control" asp-items="ViewBag.TipoDePagoID"></select>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Registrar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br />
<div>
    <a asp-action="Index">Regresar</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Trekstore/Views/PurchaseDetails/Delete.cshtml
@model Trekstore.Models.PurchaseDetails

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Eliminar</h1>

<h3>Seguro que desea eliminar esto?</h3>
<div>
    <h4>Detalle de Compra</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PurchDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PurchDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductDescription)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Provider)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Provider.ProviderID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TipoDePago)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TipoDePago.tipoPagoID)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="purch_id" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Regresar</a>
    </form>
</div>

Trekstore/Views/PurchaseDetails/Details.cshtml
@model Trekstore.Models.PurchaseDetails

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>PurchaseDetails</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PurchDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PurchDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductDescription)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Provider)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Provider.ProviderID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TipoDePago)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TipoDePago.tipoPagoID)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.purch_id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Trekstore/Views/PurchaseDetails/Edit.cshtml
@model Trekstore.Models.PurchaseDetails

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editar</h1>

<h4>Detalle de Compra</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="purch_id" />
            <div class="form-group">
                <label asp-for="Amount" class="control-label">Cantidad</label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PurchDate" class="control-label">Fecha de Compra</label>
                <input asp-for="PurchDate" class="form-control" />
                <span asp-validation-for="PurchDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductID" class="control-label">Producto</label>
                <select asp-for="ProductID" class="form-control" asp-items="ViewBag.ProductID"></select>
                <span asp-validation-for="ProductID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProviderID" class="control-label">Proveedor</label>
                <select asp-for="ProviderID" class="form-control" asp-items="ViewBag.ProviderID"></select>
                <span asp-validation-for="ProviderID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoDePagoID" class="control-label"></label>
                <select asp-for="TipoDePagoID" class="form-control" asp-items="ViewBag.TipoDePagoID"></select>
                <span asp-validation-for="TipoDePagoID" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br />
<div>
    <a asp-action="Index">Regresar</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Trekstore/Views/PurchaseDetails/Index.cshtml
@model IEnumerable<Trekstore.Models.PurchaseDetails>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Reporte de Compras</h1>

<p>
    <a asp-action="Create">Agregar Nuevo Compra</a> |
    <a asp-controller="Providers" asp-action="Index">Agregar Proveedor</a>

</p>

<form method="get" asp-controller="PurchaseDetails" asp-action="Index">
    <div class="form-row">
        <div class="col-md-12
mb-3">
            <input type="text" name="searchString" class="form-control" placeholder="Buscar por nombre de producto" value="@ViewData["CurrentFilter"]" />
        </div>
        <div class="col-md-6 mb-3">
            <div class="input-group">
                <input type="date" name="startDate" class="form-control" value="@ViewData["CurrentStartDate"]" />
                <div class="input-group-prepend">
                    <span class="input-group-text"> a </span>
                </div>
                <input type="date" name="endDate" class="form-control" value="@ViewData["CurrentEndDate"]" />
            </div>
        </div>
        <div class="col-md-3 mb-3">
            <input type="submit" value="Buscar" class="btn btn-primary" />
        </div>
    </div>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                Producto

            </th>
            <th>
                Cantidad
            </th>
            <th>
                Proveedor

            </th>
            <th>
                Fecha de Compra

            </th>
            <th>
                Tipo De Pago
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.ProductName)

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Amount)

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Provider.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PurchDate)

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TipoDePago.tipoPago)
                </td>
                <td>
                    @if (ViewContext.HttpContext.User.IsInRole("Administrador"))
                    {
                        <a asp-action="Edit" asp-route-id="@item.purch_id">Editar | </a>
                        <a asp-action="Delete" asp-route-id="@item.purch_id">Eliminar</a>
                    }

                    @if (ViewContext.HttpContext.User.IsInRole("Supervisor"))
                    {
                        <a asp-action="Edit" asp-route-id="@item.purch_id">Editar</a>

                    }
                </td>
            </tr>
        }
    </tbody>
</table>