Trekstore/Models/SalesDetails.cs
using System.ComponentModel.DataAnnotations;

namespace Trekstore.Models
{
    public class SalesDetails
    {
        [Key] public int SalesDetailsID { get; set; }

        public int Amount { get; set; }

        public DateTime Date { get; set; }

        public int? ProductId { get; set; }

        public int? ClientId { get; set; }

        public int? TipoDePagoID { get; set; }

        public virtual Client? Clients { get; set; }

        public virtual Products? Product { get; set; }

        public virtual TipoDePago? TipoDePago{ get; set; }


    }
}

Trekstore/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Trekstore.Areas.Identity.Data;
using Trekstore.Models;

namespace Trekstore.Controllers
{
    [Authorize]
    public class ClientsController : Controller
    {
        private readonly TrekstorDbContext _context;

        public ClientsController(TrekstorDbContext context)
        {
            _context = context;
        }

        // GET: Clients
        public async Task<IActionResult> Index()
        {
            return View(await _context.Client.ToListAsync());
        }

        // GET: Clients/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Client
                .FirstOrDefaultAsync(m => m.ClientId == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // GET: Clients/Create

        public IActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClientId,FirstName,LastName,PhoneNumber,Email")] Client client)
        {
            if (ModelState.IsValid)
            {
                _context.Add(client);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clients/Edit/5
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Client.FindAsync(id);
            if (client == null)
            {
                return NotFound();
            }
            return View(client);
        }

        // POST: Clients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrador")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ClientId,FirstName,LastName,PhoneNumber,Email")] Client client)
        {
            if (id != client.ClientId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(client);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientExists(client.ClientId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clients/Delete/5
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Client
                .FirstOrDefaultAsync(m => m.ClientId == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // POST: Clients/Delete/5
        [Authorize(Roles = "Administrador")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var client = await _context.Client.FindAsync(id);
            if (client != null)
            {
                _context.Client.Remove(client);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClientExists(int id)
        {
            return _context.Client.Any(e => e.ClientId == id);
        }
    }
}

Trekstore/Controllers/SalesDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Trekstore.Areas.Identity.Data;
using Trekstore.Models;

namespace Trekstore.Controllers
{
    public class SalesDetailsController : Controller
    {

        private readonly TrekstorDbContext _context;

        public SalesDetailsController(TrekstorDbContext context)
        {
            _context = context;
        }

        // GET: SalesDetails
        [Authorize(Roles = "Administrador, Supervisor, Ventas")]
        public async Task<IActionResult> Index(string searchString)
        {
            var salesDetails = from s in _context.SalesDetails.Include(s => s.Clients).Include(s => s.Product).Include(s=>s.TipoDePago)
                               select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                salesDetails = salesDetails.Where(s => s.Clients.FirstName.Contains(searchString) || s.Clients.LastName.Contains(searchString));
            }

            return View(await salesDetails.ToListAsync());
        }

        // GET: SalesDetails/Details/5
        [Authorize(Roles = "Administrador, Supervisor")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var salesDetails = await _context.SalesDetails
                .Include(s => s.Clients)
                .Include(s => s.Product)
                .Include(s => s.TipoDePago)
                .FirstOrDefaultAsync(m => m.SalesDetailsID == id);
            if (salesDetails == null)
            {
                return NotFound();
            }

            return View(salesDetails);
        }

        // GET: SalesDetails/Create
        [Authorize(Roles = "Administrador, Supervisor, Ventas")]
        public IActionResult Create()
        {
            ViewData["ClientId"] = new SelectList(_context.Client, "ClientId", "FirstName");
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductName");
            ViewData["TipoDePagoID"] = new SelectList(_context.TipoDePago, "tipoPagoID", "tipoPago");
            return View();
        }

        // POST: SalesDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = " Administrador, Supervisor,Ventas")]
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create([Bind("SalesDetailsID,Amount,Date,ProductId,ClientId, TipoDePagoID")] SalesDetails salesDetails)
        {
            if (ModelState.IsValid)
            {
                var product = await _context.Products.FindAsync(salesDetails.ProductId);
                if (product != null && product.InStock >= salesDetails.Amount)
                {
                    product.InStock -= salesDetails.Amount;
                    _context.Add(salesDetails);
                    await _context.SaveChangesAsync();

                    if (product.InStock <= 10)
                    {
                        TempData["AlertMessage"] = "Producto bajo en existencias, adquirir más productos.";
                    }

                    return RedirectToAction(nameof(Index));
                }

                ModelState.AddModelError("", "Existencias insuficientes para el producto seleccionado.");
            }

            ViewData["ClientId"] = new SelectList(_context.Client, "ClientId", "FirstName", salesDetails.ClientId);
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductName", salesDetails.ProductId);
            ViewData["TipoDePagoID"] = new SelectList(_context.TipoDePago, "tipoPagoID", "tipoPago", salesDetails.TipoDePagoID);
            return View(salesDetails);
        }

        // GET: SalesDetails/Edit/5
        [Authorize(Roles = "Administrador, Supervisor")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var salesDetails = await _context.SalesDetails.FindAsync(id);
            if (salesDetails == null)
            {
                return NotFound();
            }
            ViewData["ClientId"] = new SelectList(_context.Client, "ClientId", "FirstName", salesDetails.ClientId);
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductDescription", salesDetails.ProductId);
            ViewData["TipoDePagoID"] = new SelectList(_context.TipoDePago, "tipoPagoID", "tipoPago", salesDetails.TipoDePagoID);
            return View(salesDetails);
        }

        // POST: SalesDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrador, Supervisor")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SalesDetailsID,Amount,Date,ProductId,ClientId,TipoDePagoID")] SalesDetails salesDetails)
        {
            if (id != salesDetails.SalesDetailsID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(salesDetails);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SalesDetailsExists(salesDetails.SalesDetailsID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClientId"] = new SelectList(_context.Client, "ClientId", "FirstName", salesDetails.ClientId);
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductName", salesDetails.ProductId);
            ViewData["TipoDePagoID"] = new SelectList(_context.TipoDePago, "tipoPagoID", "tipoPago", salesDetails.TipoDePagoID);
            return View(salesDetails);
        }

        // GET: SalesDetails/Delete/5
        [Authorize(Roles = "Administrador, Supervisor")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var salesDetails = await _context.SalesDetails
                .Include(s => s.Clients)
                .Include(s => s.Product)
                .Include(s => s.TipoDePago)
                .FirstOrDefaultAsync(m => m.SalesDetailsID == id);
            if (salesDetails == null)
            {
                return NotFound();
            }

            return View(salesDetails);
        }

        // POST: SalesDetails/Delete/5
        [Authorize(Roles = "Administrador, Supervisor")]

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var salesDetails = await _context.SalesDetails.FindAsync(id);
            if (salesDetails != null)
            {
                _context.SalesDetails.Remove(salesDetails);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SalesDetailsExists(int id)
        {
            return _context.SalesDetails.Any(e => e.SalesDetailsID == id);
        }
    }
}

Trekstore/Views/SalesDetails/Create.cshtml
@model Trekstore.Models.SalesDetails

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Agregar Venta</h1>
@if (TempData["AlertMessage"] != null)
{
    <div class="alert alert-warning">
        @TempData["AlertMessage"]
    </div>
}


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label">Cantidad</label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label">Fecha de Venta</label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label">Producto</label>
                <select asp-for="ProductId" class="form-control" asp-items="ViewBag.ProductId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ClientId" class="control-label">Cliente</label>
                <select asp-for="ClientId" class="form-control" asp-items="ViewBag.ClientId"></select>
            </div>
            <div class="form-group">
                <label asp-for="TipoDePagoID" class="control-label"></label>
                <select asp-for="TipoDePagoID" class="form-control" asp-items="ViewBag.TipoDePagoID"></select>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Registrar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br />
<div>
    <a asp-action="Index">Regresar</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Trekstore/Views/SalesDetails/Delete.cshtml
@model Trekstore.Models.SalesDetails

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Eliminar</h1>

<h3>Seguro que desea eliminar esto?</h3>
<div>
    <h4>SalesDetails</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Clients)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Clients.ClientId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductDescription)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TipoDePago)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TipoDePago.tipoPagoID)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="SalesDetailsID" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Regresar</a>
    </form>
</div>

Trekstore/Views/SalesDetails/Details.cshtml
@model Trekstore.Models.SalesDetails

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>SalesDetails</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Clients)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Clients.ClientId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductDescription)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TipoDePago)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TipoDePago.tipoPagoID)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.SalesDetailsID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Trekstore/Views/SalesDetails/Edit.cshtml
@model Trekstore.Models.SalesDetails

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editar</h1>

<h4>Detalle de Venta</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SalesDetailsID" />
            <div class="form-group">
                <label asp-for="Amount" class="control-label">Cantidad</label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label">Fecha de Venta</label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label">Producto</label>
                <select asp-for="ProductId" class="form-control" asp-items="ViewBag.ProductId"></select>
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClientId" class="control-label">Cliente</label>
                <select asp-for="ClientId" class="form-control" asp-items="ViewBag.ClientId"></select>
                <span asp-validation-for="ClientId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoDePagoID" class="control-label"></label>
                <select asp-for="TipoDePagoID" class="form-control" asp-items="ViewBag.TipoDePagoID"></select>
                <span asp-validation-for="TipoDePagoID" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br />
<div>
    <a asp-action="Index">Regresar</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Trekstore/Views/SalesDetails/Index.cshtml
@model IEnumerable<Trekstore.Models.SalesDetails>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Reporte de Ventas</h1>

<p>
    <a asp-controller="Clients" asp-action="Index">Clientes </a> |
    <a asp-action="Create">Nueva Venta</a>
</p>
<form method="get" asp-controller="SalesDetails" asp-action="Index">
    <div class="form-group">
        <input type="text" name="searchString" class="form-control" placeholder="Buscar por nombre de producto" value="@ViewData["CurrentFilter"]" />
        <br />
        <input type="submit" value="Buscar" class="btn btn-primary" />
    </div>
</form>
<br />
<table class="table">
    <thead>
        <tr>
            <th>
                Producto
            </th>
            <th>
                Cantidad
            </th>
            <th>
                Primer Nombre del Cliente
            </th>
            <th>
                Apellido
            </th>
            <th>
                Fecha
            </th>
            <th>
                Tipo de Pago
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.ProductName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Amount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Clients.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Clients.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TipoDePago.tipoPago)
                </td>

                <td>
                    @if (ViewContext.HttpContext.User.IsInRole("Administrador"))
                    {
                        <a asp-action="Edit" asp-route-id="@item.SalesDetailsID">Editar</a>
                        <a asp-action="Delete" asp-route-id="@item.SalesDetailsID">Eliminar</a>
                    }

                    @if (ViewContext.HttpContext.User.IsInRole("Supervisor"))
                    {
                        <a asp-action="Edit" asp-route-id="@item.SalesDetailsID">Editar</a>

                    }
                </td>
            </tr>
        }
    </tbody>
</table>